services:
  postgres:
    image: postgres:17
    container_name: eco_trace_db
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eco_trace_backend
    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY:?Falta SECRET_KEY en .env}
      EMAIL_HOST: ${EMAIL_HOST:?Falta EMAIL_HOST en .env}
      EMAIL_PORT: ${EMAIL_PORT:?Falta EMAIL_PORT en .env}
      EMAIL_USER: ${EMAIL_USER:?Falta EMAIL_USER en .env}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD:?Falta EMAIL_PASSWORD en .env}

    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eco_trace_frontend
    restart: unless-stopped

    ports:
      - "5173:5173"

    depends_on:
      - backend

volumes:
  postgres_data:
